server {
    listen 80;
    server_name patosgym.com.ar www.patosgym.com.ar;

    # Upload size para videos de staff
    client_max_body_size 100M;
    
    # Compresión
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # Static files (Asegúrate de mapear esta ruta en villex_nginx)
    location /static/ {
        alias /srv/patosgym/volumes/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Media files
    location /media/ {
        alias /srv/patosgym/volumes/media/;
        expires 7d;
    }

    # Proxy a Gunicorn (docker-compose: patosgym_prod_web)
    location / {
        proxy_pass http://172.17.0.1:18082;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # Le dice a Django que la conexion original de CF vino por HTTPS
        proxy_set_header X-Forwarded-Proto https;
    }
}
