# Generated by Django 4.2.9 on 2026-01-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen para el carrusel del hero (recomendado: 1920x1080 o superior)', upload_to='hero/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, help_text='Título opcional para SEO/alt text', max_length=100, verbose_name='Título')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número menor aparece primero', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen Hero',
                'verbose_name_plural': 'Imágenes Hero',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('puesto', models.CharField(choices=[('dueno', 'Dueño'), ('musculacion', 'Profesor de Musculación'), ('funcional', 'Profesor de Funcional'), ('clases', 'Profesor de Clases Grupales'), ('personal', 'Personal Trainer'), ('recepcion', 'Recepción'), ('otro', 'Otro')], max_length=50, verbose_name='Puesto')),
                ('foto', models.ImageField(blank=True, help_text='Imagen del miembro del equipo', null=True, upload_to='staff/', verbose_name='Foto')),
                ('cv_info', models.TextField(blank=True, help_text='Información sobre experiencia y trayectoria', verbose_name='Bio / Experiencia')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número menor aparece primero', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
