# Generated by Django 4.2.9 on 2026-02-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL del video de YouTube (puede ser privado o unlisted). Ejemplo: https://www.youtube.com/watch?v=...', null=True, verbose_name='Video de Entrevista (YouTube)'),
        ),
    ]
