# Generated by Django 4.2.9 on 2026-02-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_teammember_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='puesto_secundario',
            field=models.CharField(blank=True, choices=[('dueno', 'Dueño'), ('duena', 'Dueña'), ('profesor_musculacion', 'Profesor de Musculación'), ('profesora_musculacion', 'Profesora de Musculación'), ('personal_trainer', 'Personal Trainer'), ('recepcionista', 'Recepcionista'), ('otro', 'Otro')], help_text='Puesto adicional (opcional). Ej: Personal Trainer si también es profesor', max_length=50, null=True, verbose_name='Puesto Secundario'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='puesto',
            field=models.CharField(choices=[('dueno', 'Dueño'), ('duena', 'Dueña'), ('profesor_musculacion', 'Profesor de Musculación'), ('profesora_musculacion', 'Profesora de Musculación'), ('personal_trainer', 'Personal Trainer'), ('recepcionista', 'Recepcionista'), ('otro', 'Otro')], max_length=50, verbose_name='Puesto Principal'),
        ),
    ]
