# Generated by Django 4.2.9 on 2026-03-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_teammember_puesto_secundario_alter_teammember_puesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='video_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='video_file',
            field=models.FileField(blank=True, help_text='Archivo de video en formato .mp4 (Peso máximo recomendado: 30MB). Reemplaza al link de YouTube.', null=True, upload_to='staff_videos/', verbose_name='Video de Entrevista (MP4)'),
        ),
    ]
