# Generated by Django 4.2.9 on 2026-03-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(choices=[('vestuarios', 'Vestuarios'), ('cardio', 'Cardio'), ('musculacion', 'Musculación'), ('transformaciones', 'Antes y Después'), ('atletas', 'Nuestros Atletas')], max_length=50, verbose_name='Categoría'),
        ),
    ]
